[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.3.1"
  export = ["tosalesforce"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/ManualTrigger","Category/Integration"]
  name = "tosalesforce"
  org = "infosyslmited"
  version = "3.1.0"

